spring:
  profiles:
    active: dev
  application:
    name: cex-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        enabled: ${NACOS_CONFIG_ENABLED:false}
    sentinel:
      enabled: ${SENTINEL_ENABLED:false}
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}

server:
  port: 18081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [traceId:%X{traceId}]"
